baseURL: http://tixie.name
languageCode: en-us
title: Tixie homepage ğŸ 
disableKinds:
- taxonomy
- taxonomyTerm
enableRobotsTXT: true
markup:
  goldmark:
    renderer:
      unsafe: true
summaryLength: 40
